# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: false

    - name: Set up NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: frontend-src/pnpm-lock.yaml
    
    - name: Build frontend
      run: |
        cd frontend-src
        pnpm install
        pnpm build

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      run: go build -tags release -v .

    - name: Test
      run: go test -v .

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: remote-agent-linux-amd64
        path: remote-agent
